# Generated by Django 3.2.25 on 2025-07-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
