# Generated by Django 3.2.25 on 2025-07-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagementApp', '0003_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_cancelled',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
