# Generated by Django 3.2.25 on 2025-07-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagementApp', '0004_booking_is_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_cancelled',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=10),
        ),
    ]
