# Generated by Django 3.2.25 on 2025-07-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagementApp', '0005_alter_booking_is_cancelled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created_at',
            new_name='booked_on',
        ),
    ]
