# Generated by Django 3.2.25 on 2025-07-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagementApp', '0007_auto_20250709_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment done', 'Payment Done')], default='Pending', max_length=20),
        ),
    ]
